/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoadBalancer;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import static java.lang.Integer.parseInt;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.SwingWorker;

/**
 *
 * @author omp
 */
public class LoadBalancer_GUI extends javax.swing.JFrame {

    int port_forclient = 0;
    int port_formonitor = 0;
    int port_forserver = 0;
    int id_client = 0;

    ArrayList<String> list = new ArrayList<String>();
    HashMap<Integer, Socket> hash_clientes_connect = new HashMap<>();
    HashMap<Integer, Socket> allServerSocketsConnected = new HashMap<>();
    HashMap<Integer, Socket> all_clientessocket_conectados = new HashMap<>();
    HashMap<Integer, ArrayList> allRequestsOnEachServer = new HashMap<>();
    ServerSocket ss_forServer = null;
    Socket s_forServer = null;

    /**
     * Creates new form LoadBalancer_GUI
     */
    public LoadBalancer_GUI() {
        initComponents();
        ONLINE_SWING.setVisible(false);

    }

    public void Start_LoadBalancer() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        numberport = new javax.swing.JTextField();
        StartButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        port_monito = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Port_Server_Swing = new javax.swing.JTextField();
        ONLINE_SWING = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOAD_BALANCER");

        jLabel2.setText("Port_Client:");

        numberport.setText("11111");
        numberport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberportActionPerformed(evt);
            }
        });

        StartButton.setText("Start");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Port_Monitor:");

        port_monito.setText("11112");
        port_monito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                port_monitoActionPerformed(evt);
            }
        });

        jLabel4.setText("Port_Server");

        Port_Server_Swing.setText("11113");
        Port_Server_Swing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Port_Server_SwingActionPerformed(evt);
            }
        });

        ONLINE_SWING.setForeground(new java.awt.Color(0, 255, 0));
        ONLINE_SWING.setText("ONLINE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(port_monito, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(Port_Server_Swing))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StartButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ONLINE_SWING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numberport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(port_monito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Port_Server_Swing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ONLINE_SWING))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numberportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberportActionPerformed

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed

        ONLINE_SWING.setVisible(true);
        ONLINE_SWING.setForeground(new java.awt.Color(0, 100, 0));
        ONLINE_SWING.setText("ONLINE!");

        port_forclient = Integer.parseInt(numberport.getText());
        port_formonitor = Integer.parseInt(port_monito.getText());
        port_forserver = Integer.parseInt(Port_Server_Swing.getText());
        ServerSocket ss_formonitor = null;
        try {
            ss_formonitor = new ServerSocket(port_formonitor);
        } catch (IOException ex) {
            Logger.getLogger(LoadBalancer_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        ServerSocket ss_forclient = null;
        InputStream inputfromclient = null;
        OutputStream outforclient = null;

        class Connect_servidor extends Thread {

            public Connect_servidor() {

            }

            public void run() {
                InputStream inputfromservidor = null;
                OutputStream outforservidor = null;
                int id_servidor = 0;

                while (true) {

                    try {
                        //ligacao load-servidor
                        s_forServer = ss_forServer.accept();
                    } catch (IOException ex) {
                        Logger.getLogger(LoadBalancer_GUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        inputfromservidor = s_forServer.getInputStream();
                    } catch (IOException ex) {
                        Logger.getLogger(LoadBalancer_GUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        outforservidor = s_forServer.getOutputStream();
                    } catch (IOException ex) {
                        Logger.getLogger(LoadBalancer_GUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    DataInputStream data_inputfromservidor = new DataInputStream(inputfromservidor);
                    DataOutputStream data_outforservidor = new DataOutputStream(outforservidor);
                    String mensagem_servidor = new String();
                    try {
                        mensagem_servidor = data_inputfromservidor.readUTF();
                    } catch (IOException ex) {
                        Logger.getLogger(LoadBalancer_GUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if ("servidor".equals(mensagem_servidor)) {
                        System.out.println("enviar id para servidor " + id_servidor);
                        try {
                            data_outforservidor.writeUTF(String.valueOf(id_servidor));
                        } catch (IOException ex) {
                            Logger.getLogger(LoadBalancer_GUI.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        allServerSocketsConnected.put(id_servidor, s_forServer);
                        allRequestsOnEachServer.put(id_servidor, new ArrayList<String>());
                        id_servidor++;
                    }

                }

            }

        }

        int counter = 0;

        Socket s_formonitor = null;
        try {
            s_formonitor = ss_formonitor.accept();
        } catch (IOException ex) {
            Logger.getLogger(LoadBalancer_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ss_forServer = new ServerSocket(port_forserver);
        } catch (IOException ex) {
            Logger.getLogger(LoadBalancer_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ss_forclient = new ServerSocket(port_forclient);
        } catch (IOException ex) {
            Logger.getLogger(LoadBalancer_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        Connect_servidor connect_server = new Connect_servidor();
        connect_server.start();
        while (true) {

            //ligacao cliente-load
            Socket s_forclient = null;
            try {
                s_forclient = ss_forclient.accept();
            } catch (IOException ex) {
                Logger.getLogger(LoadBalancer_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                inputfromclient = s_forclient.getInputStream();
            } catch (IOException ex) {
                Logger.getLogger(LoadBalancer_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                outforclient = s_forclient.getOutputStream();
            } catch (IOException ex) {
                Logger.getLogger(LoadBalancer_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            DataInputStream data_inputfromclient = new DataInputStream(inputfromclient);
            DataOutputStream data_outforclient = new DataOutputStream(outforclient);
            String mensagem_client = new String();
            try {
                mensagem_client = data_inputfromclient.readUTF();
            } catch (IOException ex) {
                Logger.getLogger(LoadBalancer_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            if ("cliente".equals(mensagem_client)) {
                System.out.println("enviar id para client " + id_client);
                try {
                    data_outforclient.writeUTF(String.valueOf(id_client));
                } catch (IOException ex) {
                    Logger.getLogger(LoadBalancer_GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                all_clientessocket_conectados.put(id_client, s_forclient);
                id_client++;
            }

            ThreadLoadBalancer t = new ThreadLoadBalancer(s_forclient, s_formonitor, s_forServer, all_clientessocket_conectados, allServerSocketsConnected, allRequestsOnEachServer);
            t.start();

            try {
                connect_server.join();
            } catch (InterruptedException ex) {
                Logger.getLogger(LoadBalancer_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                t.join();
            } catch (InterruptedException ex) {
                Logger.getLogger(LoadBalancer_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_StartButtonActionPerformed

    private void port_monitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_port_monitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_port_monitoActionPerformed

    private void Port_Server_SwingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Port_Server_SwingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Port_Server_SwingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException, InterruptedException {
        LoadBalancer_GUI exe = new LoadBalancer_GUI();
        exe.setVisible(true);

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadBalancer_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadBalancer_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadBalancer_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadBalancer_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ONLINE_SWING;
    private javax.swing.JTextField Port_Server_Swing;
    private javax.swing.JButton StartButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField numberport;
    private javax.swing.JTextField port_monito;
    // End of variables declaration//GEN-END:variables
}
